### ISSUE TITLE
Test results not found

### ISSUE THREAD

**Issue by bravetarget** [webbertakken/unity-test-runner#31]
### Configuration
```
name: Build project

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        testMode:
          - playmode
    steps:
    
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
    
      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.3
        with:
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts

      # Output 
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: ${{ steps.tests.outputs.artifactsPath }}
```
### Output
```
###########################
#    Project directory    #
###########################

total 44K
drwxr-xr-x 9 1001  115 4.0K Feb 11 17:18 .
drwxr-xr-x 5 root root 4.0K Feb 11 17:18 ..
drwxr-xr-x 9 1001  115 4.0K Feb 11 17:16 .git
-rw-r--r-- 1 1001  115   66 Feb 11 17:16 .gitattributes
drwxr-xr-x 3 1001  115 4.0K Feb 11 17:16 .github
-rw-r--r-- 1 1001  115 1.2K Feb 11 17:16 .gitignore
drwxr-xr-x 2 1001  115 4.0K Feb 11 17:16 .vscode
drwxr-xr-x 4 1001  115 4.0K Feb 11 17:16 Assets
drwxr-xr-x 2 1001  115 4.0K Feb 11 17:16 Packages
drwxr-xr-x 2 1001  115 4.0K Feb 11 17:16 ProjectSettings
drwxr-xr-x 2 root root 4.0K Feb 11 17:18 playmode-artifacts
/steps/run_tests.sh: line 147: [: =: unary operator expected

###########################
#    Play Mode Results    #
###########################

cat: /github/workspace/playmode-artifacts/playmode-results.xml: No such file or directory
cat: /github/workspace/playmode-artifacts/playmode-results.xml: No such file or directory
/steps/run_tests.sh: line 171: [: -gt: unary operator expected
##[error]The process '/usr/bin/docker' failed with exit code 1
##[error]Node run failed with exit code 1
```

Any ideas?  Tested this in a barebones project with a single unit test
