### ISSUE TITLE
Getting Unexpected Exit Code 139 (specific versions, usually beta)

### ISSUE THREAD

**Issue by pablothedolphin** [webbertakken/unity-test-runner#54]
This happens regardless of the editor version I use and regardless of either play mode or edit mode tests. It seems like the personal license is working so I'm struggling to see what's wrong:

Requesting activation (personal license)
Activation complete.
Using project path "/github/workspace/Test-Project".
Using artifacts path "editmode-artifacts" to save test results.
Using custom parameters .
Edit mode selected for testing.
Using Unity version "2020.1.0b4" to test.

###########################
#    Artifacts folder     #
###########################

Creating "/github/workspace/editmode-artifacts" if it does not exist.

###########################
#    Project directory    #
###########################

total 20K
drwxr-xr-x 5 1001 115 4.0K Apr  3 04:44 .
drwxr-xr-x 6 1001 115 4.0K Apr  3 04:46 ..
drwxr-xr-x 4 1001 115 4.0K Apr  3 04:44 Assets
drwxr-xr-x 2 1001 115 4.0K Apr  3 04:44 Packages
drwxr-xr-x 2 1001 115 4.0K Apr  3 04:44 ProjectSettings

###########################
#   Testing in EditMode   #
###########################

Segmentation fault (core dumped)
[Licensing::Module] Channel doesn't exist: "LicenseClient-root"
[Licensing::Module] Successfully launched the LicensingClient (PId: 70)
[Licensing::Module] Successfully connected to LicensingClient on channel: "LicenseClient-root"
[SignatureVerifier] Application signature verification not supported on this platform.
Entitlement-based licensing initiated
[LicensingClient] Licenses updated successfully
Unexpected exit code 139
/steps/run_tests.sh: line 109: [: =: unary operator expected

###########################
#    Project directory    #
###########################

total 20K
drwxr-xr-x 5 1001 115 4.0K Apr  3 04:44 .
drwxr-xr-x 6 1001 115 4.0K Apr  3 04:46 ..
drwxr-xr-x 4 1001 115 4.0K Apr  3 04:44 Assets
drwxr-xr-x 2 1001 115 4.0K Apr  3 04:44 Packages
drwxr-xr-x 2 1001 115 4.0K Apr  3 04:44 ProjectSettings

###########################
#    Edit Mode Results    #
###########################

cat: /github/workspace/editmode-artifacts/editmode-results.xml: No such file or directory
cat: /github/workspace/editmode-artifacts/editmode-results.xml: No such file or directory
/steps/run_tests.sh: line 164: [: =: unary operator expected
/steps/run_tests.sh: line 182: [: -gt: unary operator expected
##[error]The process '/usr/bin/docker' failed with exit code 139

**Comment by webbertakken** [comment]
Hey @pablothedolphin adn thanks for reporting your issue!

Could you also show your workflow configuration for your test job?

**Comment by pablothedolphin** [comment]
Here's my action script:

Thanks for the quick response @webbertakken ! Here it is:
```
name: Run Unit Tests

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  testAllModes:
    name: Test in ${{ matrix.testMode }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - Test-Project
        unityVersion:
          - 2019.3.6f1
          - 2020.1.0b4
        testMode:
          - editmode
          - playmode
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: |
            Library-
      - uses: webbertakken/unity-test-runner@v1.6
        id: tests
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
      - uses: actions/upload-artifact@v1
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}
```

My best guess is that the license activates fine but it fails to open the editor / the editor is crashing somehow.
