### ISSUE TITLE
Unexpected Input 'artifactsPath'

### ISSUE THREAD

**Issue by fahall** [webbertakken/unity-test-runner#60]
When I define a custom artifacts path, I get this warning:

`##[warning]Unexpected input 'artifactsPath', valid inputs are ['unityVersion']`

My yaml for the testing step is:

```yaml
      - name: Run tests
        id: tests
        uses: webbertakken/unity-test-runner@v1.6
        with:
          unityVersion: ${{ matrix.unityVersion }}
          artifactsPath: .artifacts
```

I see in `inputs.js` and in the documentation that `artifactsPath` is an accepted input. 

Am I just doing something wrong, or are the inputs not quite configured properly? This is similar, but not identical to #57 .
