### ISSUE TITLE
Timeout if projectPath ends with tilde (~) 

### ISSUE THREAD

**Issue by jsm174** [webbertakken/unity-test-runner#62]
Hello.

When we were trying to use this action, the folder structure of our project was such that Unity would get in an endless loop of finding DLLs. (ie from the project library directory and from our packages source)

In order to get Unity to ignore the project directory, I renamed it to end with a tilde:

```
jobs:
  testAllModes:
    name: Test in ${{ matrix.testMode }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - VisualPinball.Unity/Unity-Test-Project-2019.4~ 
        unityVersion:
          - 2019.4.1f1
        testMode:
          - editmode
```

When I try to run this action when `projectPath` ends in the tilde, it just sits for hours and eventually times out:

```
Run failed for unity-workflow-3 (029e4dd)
Repository: jsm174/vpe_net_standard
Workflow: Build project
Duration: 6 hours and 14.0 seconds
Finished: 2020-06-27 07:02:19 UTC

View results

Jobs:
Test in editmode on version 2019.4.1f1 cancelled (5 annotations)
```

This morning I renamed the project to begin with a period, and had no issues getting it to run.

```
      projectPath:
          - VisualPinball.Unity/.Unity-Test-Project-2019.4 
```
